name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: xanderhendriks/stm32cubeide:7.0
      options: --user root

    steps:
    - name: Wait for container to be ready
      run: sleep 5
    - uses: actions/checkout@v3
    - name: Build
      run: |
        stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data workspace -importAll $(pwd) -cleanBuild all
