name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: krasnianskyi/stm32cubeide:latest
      options: --user root

    steps:
    - uses: actions/checkout@v3
    - name: Check PATH
      run: echo $PATH
    - name: Set PATH
      run: export PATH="/opt/stm32cubeide_$STM32_CUBE_IDE_VERSION/bin:${PATH}"
    - name: Build
      run: |
        stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data workspace -importAll $(pwd) -cleanBuild all
